### ISSUE TITLE
Maven build is failing

### ISSUE THREAD

**Issue by ijabz** [FamilySearch/gedcom5-conversion#12]
I cloned a new copy, then ran mvn install which fails as follows:

C:\Code\genealogy\gedcom5-conversion>mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.gedcomx:gedcom5-conversion:jar:1.0.1.M1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 66, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 75, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 92, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building gedcom5-conversion 1.0.1.M1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.gedcomx:gedcomx-fileformat:jar:1.0.0.M1 is missing, no dependency information available
[WARNING] The POM for org.folg.gedcom:gedcom:jar:1.1 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.474s
[INFO] Finished at: Thu May 12 17:04:40 BST 2016
[INFO] Final Memory: 5M/415M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gedcom5-conversion: Could not resolve dependencies for project org.gedcomx:gedcom5-conversion:jar:1.0.1.M1-SNAPSHOT: T
he following artifacts could not be resolved: org.gedcomx:gedcomx-fileformat:jar:1.0.0.M1, org.folg.gedcom:gedcom:jar:1.1: Failure to find org.gedcomx:gedcomx-f
ileformat:jar:1.0.0.M1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval o
f central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by stoicflame** [comment]
Thanks for the report. Fixed now.

**Comment by githamar** [comment]
Hey, I'm glad to hear it's fixed. Thanks so much for your work.
