### ISSUE TITLE
Won't build/run with recent Java and libraries

### ISSUE THREAD

**Issue by AJAskey** [FamilySearch/gedcom5-conversion#19]
As I understand the documentation, this is the only way to convert a GEDCOM file into GEDCOM-X structure. If I am missing something please let me know how to convert my GEDCOM into GEDCOM-X structure.

If this is the only method then please update this POM / Libraries / Source to work with versions of Java beyond 1.6.

Thanks. Andy Askey

**Comment by stoicflame** [comment]
I can update and build a new version.

What's the output of `mvn -v` so I can replicate your environment?

Also note that there are a number of features still missing from the conversion, so it's not a "full" conversion yet.

**Comment by stoicflame** [comment]
Fixed at d972802e97e09a445475b48f5df6412e63fb935d.
